- name: Update system
  apt:
    upgrade: yes
    update_cache: yes

- name: Install essential packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Restart SSH deamon
  service:
    name: sshd
    state: restarted
  when:
    - sshd_config.changed
